[package]
name = "rose"
version = "0.1.0"
authors = ["Bruno Andreotti <bandreotti@protonmail.com>"]
description = "A Penrose tiling generator"
license = "MIT"
repository = "https://github.com/bpandreotti/rose"
edition = "2018"

[dependencies]
structopt = "0.3.19"

[dev-dependencies]
rand = "0.7.3"
